### ISSUE TITLE
Experimental saves library

### ISSUE THREAD

**Issue by dextercd** [spelunky-fyi/s2-data#3]
Hiya, I think it's a cool and good idea to create some kind of Python library around the different data formats used by Spelunky 2.  

You probably already have a plan on how you'd like to create the save library, but I think the best libraries can only be made by experimenting with many different ideas, so I wanted to share my ideas for a library around the save files.

See this branch for the code: https://github.com/dextercd/s2-data/tree/saves-library/src/s2_data

I've only worked on the static part, which defines the types and the fields. The next step would be to define a dynamic part so that it's easy to modify saves using Python.

The static part works by having types and field descriptors, the types define the conversion between the binary layout and Python values. The field descriptors are a simple class which defines the location of the field, the name/description, and its type.

The field_descriptors.py file also contains a list of fields, currently only the journal and the character unlock flags.

I used this library to build a simple program to convert save file to a textual representation so that you can use it with `git diff`, I used something similar to this for reverse engineering the various save file fields. It's just an example for how you might use the lower level parts of this experimental library.

![image](https://user-images.githubusercontent.com/14349965/96372595-d3f0a800-1167-11eb-9a04-7c7771739b99.png)

Feel free to steal these ideas or completely disregard them if you have a better idea. :smile:

**Comment by gmjosack** [comment]
Hey, i was also mostly just working on descriptors for now since i'm building a save editor in javascript and using the python library just for helping lay everything when i generate the templates server side, though I'd love to have a more fleshed out python lib, could even make a cli to just flip certain flags pretty easily. 

My original idea was going to be something similar so if you want to do a pull request I'd be happy to merge it

**Comment by dextercd** [comment]
Great! I'll continue working on it and open up a PR. I don't feel like it's ready yet.
